---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webui-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi
  volumeName: "webui-volume"