---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: madhead-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: webui-efs-retain-data-sc
  resources:
    requests:
      storage: 200Gi