apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: bottlerocket-provisioner
spec:
  providerRef:
    name: bottlerocket-2

  labels:
    billing-team: map-team
    node-type: "bottle-rocket-gpu-webui"

  annotations:
    example.com/owner: "my-team"

  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["g5.2xlarge", "g5.4xlarge"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: [ "spot", "on-demand" ]

  limits:
    resources:
      cpu: 1000

  ttlSecondsAfterEmpty: 30

  weight: 20
