apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-api-role
  namespace: default
  labels:
    from: backend-api-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "networking.k8s.io"
    resources:
      - pods
      - services
      - services/status
      - deployments
      - ingress
      - ingresses
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
      - delete
      - create